### ISSUE TITLE
Server console kept spamming “Watched item is not a BlockItem”

### ISSUE THREAD

**Issue by BugmanBugman** [hammertater/treeplant#1]
What does it mean? Possible incompatibility with another mod?

**Comment by hammertater** [comment]
Thanks for reporting this. It means the mod doesn't know how to plant a particular sapling item, probably for a modded tree. Sorry, I'll make the warning give more info in future versions.

Could you post a list of the mods that are installed? Or a log that shows the warning being spammed?

Could you also share your ‘treeplant-common.toml’ config file?

**Comment by BugmanBugman** [comment]
Ah ok, when I get back to my pc I’ll share it. Some trees with mods I have though, are BYG, BOP, mystical world, autumnity,  and atmospheric

**Comment by hammertater** [comment]
Don't worry about getting those logs -- looks like the warning message was erroneously being shown when a sapling couldn't be planted because it was too close to another sapling. Oops! I'll update the mod soon to stop those message from appearing and to give more detailed warnings.

**Comment by hammertater** [comment]
Version 0.1.1 is up and includes the fixes. I'm gonna go ahead and close this issue.
